{% if conf['db-secret'] %}
---
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: egov
type: Opaque
data:
  username: "{{conf['db-secret']['username'] | decrypt}}"
  password: "{{conf['db-secret']['password'] | decrypt}}"
  flyway-username: "{{conf['db-secret']['username'] | decrypt}}"
  flyway-password: "{{conf['db-secret']['password'] | decrypt}}"
{% endif %}    